### ISSUE TITLE
Add support for GraphQL via Apollo

### ISSUE THREAD

**Issue by advance512** [diegohaz/arc#106]
I'll be adding support for Apollo (both react-apollo and apollo-server) myself, soon. If desired, I can offer it as a Pull Request. It would be nice to be able to automatically scaffold Apollo-based containers.

Here's a nice example of how it can look:
https://github.com/saikat/react-apollo-starter-kit/blob/master/src/containers/RemoteCounter.jsx

**Comment by diegohaz** [comment]
@advance512 Sure, please. I don't have much experience with GraphQL/Apollo though.

I want to keep the master branch simple as it is, but if you want to create a repo based on ARc, I can add that to the generator as soon as it is stable (as you can see, the generator just takes git submodules: https://github.com/diegohaz/arc/tree/generator-arc/templates).

**Comment by advance512** [comment]
Please note that using this requires some changes to the application itself:

For the redux branch
1. Adding an Apollo client (probably configured in a service)
http://dev.apollodata.com/react/initialization.html#creating-client
Probably like this:
https://github.com/saikat/react-apollo-starter-kit/blob/master/src/network/apollo-client-singleton.js
2. Using the Apollo Provider instead of the standard one
http://dev.apollodata.com/react/initialization.html#creating-provider

For the universal-redux branch:
3. Add SSR:  http://dev.apollodata.com/react/server-side-rendering.html

For the full-stack, add support for an apollo-server (or just GraphQL):
4. Add a GraphQL endpoint
http://dev.apollodata.com/tools/graphql-server/setup.html
5. Define some sort of schema for demonstration purposes

generator-arc:
6. Add support for Apollo-based Component templates
https://github.com/saikat/react-apollo-starter-kit/blob/master/src/containers/RemoteCounter.jsx

Does this make sense?

GraphQL is definitely the way forward. The leading boilerplate framework (react-starter-kit) has support for it, react-boilerplate is heading there as well.

**Comment by diegohaz** [comment]
Well, that seems to be huge. But I think many developers would benefit from this since GraphQL and Apollo are getting more and more popular.

I would love to see and support a repo/fork called `arc-graphql` or something like that. Do you want to work on that?

**Comment by advance512** [comment]
Please have a look here:
https://github.com/advance512/arc/commit/2176e2524d074fe9e8dd363226f1d0c121f0eb34

This is going to be my basis for a new project. For now I'll base it on my own repository, but I do hope you'll consider merging it.

There are tests missing, and I need to update src-clean/ and also the #redux-universal branch, but it is pretty much finished.

**Comment by advance512** [comment]
I created a new PR with src-clean/ updated.
https://github.com/diegohaz/arc/pull/116

Still only #fullstack. I also have #redux branch updated.

**Comment by advance512** [comment]
Two more:
#117 
#118 

Still no new tests.

**Comment by diegohaz** [comment]
@advance512 An amazing work you are doing here. Congratulations and thank you very much. ❤️

I have some questions:

- Would it be better if it was only one branch? If so, which branch do you prefer to take as basis (like `fullstack`)?

- Based on the previous question, what do you think about having a separated branch with graphql?

- What do you think about that branch replacing the current `fullstack`?

- As you can see in [this comment of mine](https://github.com/diegohaz/arc/issues/112#issuecomment-280871584), I'm having a hard time to keep maintaining the `fullstack` branch. Would you like to maintain it if we add graphql?

- As a maintainer, what do you think about we transferring that branch for you to create a new repo? We would move that to the [**Forks**](https://github.com/diegohaz/arc#forks) section on README.md, send PRs whenever we have changes on the base branches. You'll have more flexibility and visibility.

Please, note that keeping things maintainable and constantly improved in this project is one of our most important principles. Unfortunately, I can't guarantee that with GraphQL as I currently have not enough knowledge. Because of that, I can't add it to other branches, but if you want to be maintainer I'm open to transform `fullstack` into `graphql` or transfer it for you to maintain a new repo.

Both of these options are good. 😊
