### ISSUE TITLE
CSS is not loading 

### ISSUE THREAD

**Issue by gururajjeerge** [diegohaz/arc#146]
For Redux branch CSS is not loading.
Can we have Sass loader integrated in webpack configuration ?

**Comment by diegohaz** [comment]
Hey, @gururajjeerge 

I don't want to bloat the boilerplate with things that people might not use (I personally don't use CSS/SASS at all).

But some instructions on docs (or even an example PR if someone wants to work on that) are desirable.

**Comment by mrotaru** [comment]
@gururajjeerge did you manage to get CSS/SASS working ?

**Comment by tonyhschu** [comment]
The way I got css loading to work is as follows:

First, create a `cssLoader()`, not unlike the `babal()` loader.
```js
const cssLoader = () => () => ({
  module: {
    rules: [
      { test: /\.css$/, loader: ["style-loader", "css-loader"] }
    ]
  }
})
```

Then, add it as a plug-in. (I added it just under where `babel()` was placed.
```js
...
babel(),
cssLoader(),
happypack([
  babel()
])
...
```

This enabled me to require css files for third-party components properly, like this:
```js
import 'react-virtualized/styles.css'
```
... instead of seeing errors like this in Storybook.
![screen shot 2017-08-14 at 2 04 13 pm](https://user-images.githubusercontent.com/929249/29291794-90b8198a-80f9-11e7-9b38-0329f64a2dfc.png)

Hopefully this will help other people who stumbles on this.

Also, hi @gururajjeerge!
