### ISSUE TITLE
[fullstack] Infinity loop on tests in the fullstack app

### ISSUE THREAD

**Issue by pgrekovich** [diegohaz/arc#154]
When I try to run tests with the  `npm run test`  command, the tests never start. I think the problem is in `mockgoose` or maybe in smth else , can anyone have any ideas?

**Comment by protoEvangelion** [comment]
@pgrekovich How long did you wait?  I may be experiencing something similar.  I received an error at around **200** seconds:

[![Capture.png](https://s27.postimg.org/5bh73ta4j/Capture.png)](https://postimg.org/image/ogkgdkosf/)

And then it started failing a whole bunch of tests with the error: `Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

Not sure what's going on either :confused:

**Comment by pgrekovich** [comment]
@protoEvangelion i think problem with mockgoose. You can clear file `tests\setup.js` and all test except for tests with mongo will passed. But i no idea, how to fix it :cry:

**Comment by protoEvangelion** [comment]
@diegohaz Still trying to find the root issue here.  Do PRs run through Travis CI before being merged?

**Comment by diegohaz** [comment]
@protoEvangelion Yes. Travis has reported some weird stuff on that, but it passes anyway.

**Comment by pgrekovich** [comment]
@protoEvangelion  @diegohaz maby problem in mongodb version?

**Comment by protoEvangelion** [comment]
@diegohaz @pgrekovich It was an issue with mockoose as you first suspected 👍 The problem was that **version 6.x of mockgoose was not compatible with Windows.**  

The solution was to update to **version 7.0.6**.  There were some breaking changes with the mockgoose api which I fixed mostly.  However _I can only pass 74 tests but fail on the 75th_ which is the `src/api/post/model.test.js` suite.  

I would be grateful if you could help me figure out the last test!!!   [https://github.com/diegohaz/arc/pull/167](url)

**Comment by diegohaz** [comment]
Fixed in #167 167

**Comment by pgrekovich** [comment]
@protoEvangelion  @diegohaz good job! thanks! :thumbsup:
