### ISSUE TITLE
why are both redux-thunk & redux-saga in universal-redux branch?

### ISSUE THREAD

**Issue by Andriy-Kulak** [diegohaz/arc#165]
why are both redux-thunk & redux-saga in universal-redux branch?

Also, I really like this boilerplate and and considering using it for a project for which I need a SEO friendly react app.

Because I am on a tight deadline **I prefer to use a redux-thunk**, a tool I am very familiar with, in production over saga. Is it a good idea for me to simply remove saga related code from the codebase and start using thunk or are there other adverse effects I should be aware of?

Thanks for creating this boilerplate! It's awesome!!!! :-)

**Comment by diegohaz** [comment]
Hey, @Andriy-Kulak 

`redux-thunk` is necessary here because of [`redux-form-submit`](https://github.com/diegohaz/redux-form-submit). We just need that to make `redux-form` work on server side.

I think it's ok to remove `redux-saga`. Just make sure to return the promises on page containers which you want to fetch data on server (reference: https://github.com/diegohaz/arc/tree/universal-redux#universal).

Also, consider sharing your experience and/or some steps to remove saga. Can help others.

**Comment by jt3k** [comment]
bump!

I need your experience in removing the saga
