### ISSUE TITLE
[redux] jest running test cases on containers components

### ISSUE THREAD

**Issue by brijesh-pant** [diegohaz/arc#210]
![screenshot from 2017-04-09 13 36 55](https://cloud.githubusercontent.com/assets/10848347/24835843/74777140-1d2a-11e7-8e84-0b772e1fc232.png)
Hi @diegohaz ,
First of all thanks for the wonderful boilerplate to follow atomic design. 
I'm trying to run test cases using jest. While components are testing perfectly with proper code coverage.
I'm having problems with containers which jest is trying to run test cases on and produces less coverage for those.

I'm wondering how do I have to create test cases for the containers I create.
For e.g when I created a component using redux form and a corresponding container for the same components, jest don't show any code coverage on those.

But when I create a component like LocaleSwitch and use a container for that, jest shows up less code coverage on the LocaleSwitchContainer.

Creating test cases for actions for localeswitch redux state also shows up the same less code coverage.

Here is a sample for the code 
```import React from 'react'
import { connect } from 'react-redux'

import { LocaleSwitch } from 'components/organisms';
import { i18nMessages } from 'actions/i18nActions';

const LocaleSwitchContainer = props => <LocaleSwitch {...props} />

const mapStateToProps = ({ i18n }) => ({
  locale: i18n.locale,
})

const mapDispatchToProps = (dispatch) => ({
  onChangeLocale: (locale) => dispatch(i18nMessages.request({ locale })),
})

export default connect(mapStateToProps, mapDispatchToProps)(LocaleSwitchContainer)
```

Do I need to create mockStore for the containers I'm using ?
Please let me know if anything is unclear. I'll elaborate more on it.

**Comment by diegohaz** [comment]
Hi, @brijesh-pant. Sorry about the delay.

It seems that you are using different structure from ARc since you are importing from `components/organisms` and `actions/**`.

On ARc example source, jest doesn't see containers (because we mock them [here](https://github.com/diegohaz/arc/blob/redux/package.json#L30)) and therefore doesn't generate coverage status for them. 

Usually, I don't test containers because they simply use other libraries and internal modules that already test themselves (components, store, redux, redux-form etc.).
