### ISSUE TITLE
Deploy to dist, blank index.html

### ISSUE THREAD

**Issue by whoisleon** [diegohaz/arc#26]
I did `npm run build` I looked into the public & dist folder I see a .JS and the index.html but the index is blank.  Am I doing something wrong?

**Comment by diegohaz** [comment]
Hi, @whoisleon 

Which branch are you using?

Which steps did you follow until you got to that (help me to reproduce this)?

**Comment by whoisleon** [comment]
```
$ git clone https://github.com/diegohaz/arc my-app
$ cd arc
$ npm install
$ npm run
$ npm run build

```
I looked in the dist/ folder: http://d.pr/i/Ewov
Open the index.html...blank: http://d.pr/i/iGr6

Am I doing it right?

**Comment by diegohaz** [comment]
Oh, I see. You are trying to run the app on the file system. It will not work because:

1. This is trying to download the `/app.[hash].js` file at `/`, which translates to `file:///app.[hash].js`
2. Even if you go to the `index.html` and change that to `app.[hash].js` (removing the `/` so it translates relatively to the index.html path), it will display a NotFound page because `react-router` can not run on the filesystem.

You need to run the dist folder on a server. On Mac you could simply `simplehttpserver path/to/dist` and open `http://0.0.0.0:8000`.

If you want to keep it running while you are editing the code, use `npm run dev`.
