### ISSUE TITLE
[redux] Deploy

### ISSUE THREAD

**Issue by mrTurkay** [diegohaz/arc#263]
I developed and deployed a redux application, when I run it at http-server or iis, it works normally, but when I refresh the page, it can not found the route. I have researched about it, but I could not solve it. how can I solve it? 

It seems it is not only I have that problem.

**Comment by diegohaz** [comment]
I've never heard about it. Is that related to ARc? Do you have some easy way to replicate it? What's the url you're trying to access?

**Comment by mrTurkay** [comment]
I think it is about react router. when you deploy it, it is okay, it works normally. route is also works normally. 

For example you navigate to `/about` page. it is okay. But when you refresh the page or when you type url as `localhost/about`, it starts a server request and server can not find `/about` route. then there is 404 not found error. 

I used HashRouter instead of BrowserRouter, but there is hash url is ugly.

**Comment by diegohaz** [comment]
Oh, I see. That happens because there's no server on `redux` branch, just static files. When you try to get `/about` from the server, it responds with 404 because there's no `/about` folder inside your public directory.

You need whether a server that sends all requests to `index.html` (so `react-router` can handle it) or some work around like we do on https://arc.js.org/sample-page (see https://github.com/diegohaz/arc/tree/gh-pages - without `404.html`, which is the same as `index.html`, it would return Not Found page, but that's something specific to GitHub Pages).

**Comment by diegohaz** [comment]
Related to #3

**Comment by mrTurkay** [comment]
I solved it with url rewriting on IIS. 

First, [urlrewrite download](https://www.iis.net/downloads/microsoft/url-rewrite), and install, then there is open urlrewrite module on IIS, redirect your routes with regex to route path `/`. 

it will redirect other routes such as `/about` or `/simple-page` to index.html and your react-router start to work.
