### ISSUE TITLE
404 on sample page

### ISSUE THREAD

**Issue by isaachinman** [diegohaz/arc#3]
If you load the sample page directly, it produces a 404. This page is only accessible if you load the homepage, and then navigate to the sample page. Troubling to see this, hopefully the cause is simple, or has to do with GitHub Pages?

<img width="689" alt="screen shot 2016-10-24 at 13 44 36" src="https://cloud.githubusercontent.com/assets/10575782/19644480/481acee8-99f0-11e6-94f2-00f0e1dbd08c.png">

**Comment by diegohaz** [comment]
Yeah, sadly GitHub Pages doesn't handle this.

But it works, you just need a server that redirects all requests to `index.html` so React can handle that.

I'm working on the server side rendering version right now. Probably I'll release it later today. The demo (for the server side branch only) will be deployed on Heroku and this will be solved as well.

I'll keep the redux version on GitHub Pages though, because it's the only way I can use the `js.org` DNS. 😭

**Comment by isaachinman** [comment]
Okay, got it.

**Comment by diegohaz** [comment]
SSR version (works without javascript enabled): https://arc.diegohaz.com
