### ISSUE TITLE
Add Dropdown Components

### ISSUE THREAD

**Issue by jeremyadavis** [diegohaz/arc#35]
I've found your organization and composition of components to be very helpful to my own work. To that end, I'd love to see your take on building a couple of dropdown controls.

I've got a simple dropdown component that renders out basic HTML select/options list and also a more complex one that takes in an item renderer component for more custom dropdowns.

I came here hoping to see how you would have implemented them and was disappointed to not find one in your current library.

**Comment by diegohaz** [comment]
Hi, @jeremyadavis 

Well, the project focus isn't to be a components library. I plan to publish them on npm, in the future. But the main purpose of this is to provide a nice structure for React projects. The components are just examples and/or something you can use to bootstrap your app.

Now, talking about Dropdown, I've made one on another project (see [here](https://github.com/tramaLabs/web/blob/master/src/components/organisms/UserButton/index.js#L18-L28)). The reason I didn't add that to this boilerplate is because it uses another dependency ([`react-aria-menubutton`](https://github.com/davidtheclark/react-aria-menubutton)) and I don't want to fill the boilerplate with more and more dependencies.

Tell me if it helps you.

**Comment by jeremyadavis** [comment]
It helps. Thanks for the links.
