### ISSUE TITLE
Scroll flicker 

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#90]
Cant get page no to flicker after SSR. Styles are in place but scroll glitches.

**Comment by diegohaz** [comment]
Hey, @kybarg. Is this still happening? I can't see the same behavior, can you provide some steps to reproduce it, a GIF or something else?

**Comment by kybarg** [comment]
@diegohaz Sure, Please pay attention to scrollbar behavior. And I think this just happens when server-side rendering is enabled. Cause your website seems to work fine.
[video example](https://drive.google.com/file/d/0B_3moca-zzS2UFdwQzZhLTQzQ1E/view?usp=sharing)

**Comment by diegohaz** [comment]
Oh, I see now. Thank you for the video, it helped a lot. 

I did a quick test here and it seems to be caused by `react-router-scroll`. Removing it completely from `src/client.js` (universal-redux) or `src/index.js` (master/redux) solved this problem for me. Can you try it? If it works for you, please send a PR against the master branch. :)

We would need to get rid of it anyway because `react-router-scroll` will not be supported by `react-router v4`

**Comment by diegohaz** [comment]
Reference on `react-router-scroll` README: https://github.com/taion/react-router-scroll#server-rendering

The weird part is that it also has no effect on client (at least on Chrome). It seems to be useless unless we use a custom scroll behavior.

**Comment by kybarg** [comment]
@diegohaz Definitely that was it!) Thank you so much.
